spring.application.name=back_end
spring.datasource.url=jdbc:postgresql://localhost:5432/motorcycle_dealer
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
jwt.secret = my_super_secret_key_very_long_123456
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB